### ISSUE TITLE
"Unable to determine registrant mod for codechicken.lib.render"

### ISSUE THREAD

**Issue by MegaSniperB** [Chicken-Bones/CodeChickenLib#23]
Closed

Links expired, bug no longer pertains to current version

**Comment by scyfar** [comment]
I can confirm this error (or report it again) with the following configuration:
* Minecraft 1.7.10 (Minecraft Launcher 1.6.11)
* Minecraft Forge 10.13.2.1291 (Installed with the Win-Installer)
* Java 1.8.0_31

Additional Mods:
* Lockdown 2.0.0

NEI/CCC Versions:
* 1.0.3.74/1.0.4.29
* 1.0.4.83/1.0.4.35

The Error can be reproduced with the following steps:
1. Install Minecraft 1.7.10
2. Install Minecraft Forge with the Win-Installer (or any other way)
3. Add NEI/CCC
4. Launch the game and open the inventory

[Paste of the full log](http://pastebin.com/U8VLzK17)

PS: This may belong to NotEnoughItems but it was already reported here.
