### ISSUE TITLE
Modding 1.8

### ISSUE THREAD

**Issue by diba1013** [Chicken-Bones/CodeChickenLib#36]
I'm currently modding with 1.8. If I try to put 
NEI 1.0.5.82, 
CodeCickenCore 1.0.5.34 and 
ChickenLib 1.1.2.131
into my workspace there is a window where I should select an mcp conf dir for the deobfuscator. If I select a folder it will crash with:  java.lang.RuntimeException: Could not find packaged.srg or joined.srg at codechicken.lib.asm.ObfMapping$MCPRemapper.parseConfDir(ObfMapping.java:142)

**Comment by sylphio** [comment]
download the forge userdev from forge download site.
