### ISSUE TITLE
GuiDraw.getStringWidth is incorrect for bold text

### ISSUE THREAD

**Issue by squeek502** [Chicken-Bones/CodeChickenLib#40]
Formatting codes are stripped before calculating width, meaning that bold text returns a smaller width than it should.

Relevant code:
https://github.com/Chicken-Bones/CodeChickenLib/blob/master/src/codechicken/lib/gui/GuiDraw.java#L95-L99

See also https://github.com/MinecraftForge/MinecraftForge/issues/1660

**Comment by Chicken-Bones** [comment]
Must have been left from before bold text was added
Fixed in 16f0b50920ea0133706eec87704071422bacc494 (1.7.10-1.1.3.135)
