### ISSUE TITLE
Rendering / Tessellation errors - multiple mods affected - CCExtendedBlockRendererDispatcher

### ISSUE THREAD

**Issue by MxtressMyxx** [Chicken-Bones/CodeChickenLib#66]
The following line has appeared in the crash reports of at least a dozen different testing instances across my attempts to load crash-free debug worlds:

`codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:60)` (if you google search for this verbatim you can see how many different mods are affected)

I have taken quite a bit of time trying to research the cause of this issue and I cannot determine if it is the fault of the lib or the fault of the individual mods. All I can glean from my testing efforts and research is either there is a critical fault in this function, or mod authors are using it improperly. What breaks that theory however, is that this error is called on and crashes mods that don't even depend on ccl.

Please let me know what I may do to assist in rooting out the cause of these crashes as this error .

**Comment by asiekierka** [comment]
Wrong repo. Try https://github.com/TheCBProject/CodeChickenLib

**Comment by MxtressMyxx** [comment]
And a critical misunderstanding of the issue we were having. Sorry for the noise.
